services:
  efficientad:
    image: efficientad:${CUDA_VERSION:-12.4}-cudnn-devel-ubuntu22.04
    build:
      context: .
      args:
        CUDA_VERSION: ${CUDA_VERSION:-12.4}
    container_name: efficientad
    ports:
      - 6006:6006
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]