seed: 42

dataset:
  path: data/dataset
  roi: 346:222:1262:127
  pre_transform: False

  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]

  batch_size: 1
  workers: 12

  train:
    crop: False
    hflip: False
    vflip: False
    rotate: False
    translation: False
    grayscale: False
    jitter: False
    blur: False

trainer:
  steps: 25000
  transform_steps: 22000
  test_freq_steps: 2000
  lr: 0.0001
  wd: 0.00001
  lr_scheduler:
    type: StepLR
    kwargs:
      step_size: 20000
      gamma: 0.1

net:
  input_size: 256
  type: small
  teacher_weights: models/pdn_s_wideresnet101_2.pth
  out_channels: 384

saver:
  exp_path: results/dataset